services:
  db:
    image: postgres:16
    container_name: attendance_db
    restart: always
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: attendance_user
      POSTGRES_PASSWORD: attendance_pass
    ports:
      - "5432:5432"
    volumes:
      - attendance_pgdata:/var/lib/postgresql/data

volumes:
  attendance_pgdata: